name: "Undo Latest Commit"
description: "A Github Action to undo the latest commit"
author: "mail@fabriziocacicia.com"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "black"
